package coursework;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SbytServiceImpl extends SbytApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public SbytServiceImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("coursework", /* package name */
      "SbytServiceLocal" /* Configuration Name */);
    }
}
